<?php
/**
 * PLANTILLA DE CREDENCIALES SENSIBLES.
 * COPIAR ESTE ARCHIVO A "credenciales.php" (IGNORADO POR GIT) Y COMPLETAR CON LAS CONTRASENAS REALES.
 * ESTE ARCHIVO DE EJEMPLO NUNCA DEBE CONTENER DATOS REALES NI SUBIRSE CON ELLOS.
 */
return [
    'SMTP_PASS' => 'REEMPLAZAR_POR_CONTRASENA_DEL_MAIL',
    'DB_PASS' => 'REEMPLAZAR_POR_CONTRASENA_DE_LA_BD',
];