<?php
/**
 * GA4 - EVENTO SERVER-SIDE: FORMULARIO DE CONTACTO
 * LLAMADO DESDE GestionModel.php CUANDO SE GUARDA UNA CONSULTA
 */

function ga4_track_contact($categoria, $nombre = '') {
    // EL EVENTO DE GA4 SE DISPARA EN EL FRONTEND (contacto.php) PARA NO CORROMPER RESPUESTAS JSON DE LA API
    // ESTA FUNCION SE MANTIENE POR COMPATIBILIDAD SIN SALIDA HTML DIRECTA
}
